In [1]:
import numpy as np

In [2]:
np.multiply.reduce([2,3,5])

30

In [3]:
X = np.arange(8).reshape((2,2,2))

In [4]:
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
np.add.reduce(X, 0)

array([[ 4,  6],
       [ 8, 10]])

In [6]:
np.add.reduce(X)

array([[ 4,  6],
       [ 8, 10]])

In [7]:
np.add.reduce(X, 1)

array([[ 2,  4],
       [10, 12]])

In [8]:
np.add.reduce(X, 2)

array([[ 1,  5],
       [ 9, 13]])

In [9]:
np.add.reduce([10], initial=5)

15

In [10]:
np.add.reduce([10], initial=1)

11

In [11]:
np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initial=10)

array([14., 14.])

In [12]:
a = np.array([10., np.nan, 10])

In [13]:
a

array([10., nan, 10.])

In [14]:
np.add.reduce(a, where=~np.isnan(a))

20.0

In [15]:
np.minimum.reduce([], initial=np.inf)

inf

In [16]:
np.minimum.reduce([[1., 2.], [3., 4.]], initial=10., where=[True, False])

array([ 1., 10.])